config/routes.rb
Rails.application.routes.draw do
  match 'todos/list', :controller =>'todos', :action => 'list', via: :get
  get 'todos', to: 'todos#index'
  root 'todos#index'
  get 'todos/new'
  post 'todos', to: 'todos#create'
  get 'todos/:id', to: 'todos#show', as: 'todo'
  get 'todos/:id/edit', to: 'todos#edit', as: 'edit_todo'
  patch 'todos/:id', to: 'todos#update'
  delete 'todos/:id', to: 'todos#destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
  validates :description, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  def index
    @todos = Todo.all
  end

  def new
    @todo = Todo.new
  end

  def create
    @todo = Todo.new(todo_params)
    @todo.save
    redirect_to todos_path
  end

  def show
    @todo = Todo.find(params[:id])
    if @todo.completed
      @status = 'Completado'
    else
      @status = 'No completado'
    end
  end

  def edit
    @todo = Todo.find(params[:id])
  end

  def update
    @todo = Todo.find(params[:id])
    @todo.update(todo_params)
    redirect_to todos_path
  end

  def destroy
    @todo = Todo.find(params[:id])
    @todo.destroy
    redirect_to todos_path
  end

  def list
    @todos = Todo.all
  end

  private

  def todo_params
    params.require(:todo).permit(:description, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoApp</title>
    <%= csrf_meta_tags %>

<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'navbar' %>
    <%= yield %>
  </body>
</html>

app/views/todos/_form.html.erb
<%= form_with model: @todo, local: true do |t| %>
  <div class="well well-lg">
    <%= t.label :description, "ToDo" %>
    <%= t.text_field :description %>

    <%= t.label :completed, "Listo" %>
    <%= t.check_box :completed %>

    <%= t.submit "Guardar" %>
  </div>
<% end %>

app/views/todos/_navbar.html.erb
<nav class="navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" <%= link_to "ToDos", todos_path %>"></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Index", todos_path%></li>
        <li><%= link_to "Lista ToDos", todos_list_path%></li>
        <li><%= link_to "Crear ToDo", todos_new_path%></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/todos/edit.html.erb
<h1> Editar ToDo </h1>

<%= render 'form' %>

app/views/todos/index.html.erb
<h1> Lista de ToDos </h1>

<% @todos.each do |t| %>
  <div class="well well-lg">
    <h2> <%= t.description %> </h2>
    <%= link_to 'Mostrar ToDo', todo_path(t.id), class:'btn btn-primary' %>
    <%= link_to 'Editar ToDo', edit_todo_path(t.id), class:'btn btn-success' %>
    <%= link_to "Borrar ToDo", t, method: :delete, data: {confirm: '¿Borrar ToDo?'}, class:'btn btn-danger' %>
  </div>
<% end %>

<div class="btn-group btn-group-lg">

<%= link_to 'Crear ToDo', todos_new_path, class:'btn btn-warning' %>

</div>

app/views/todos/list.html.erb
<div class="row">
  <div class="container">

    <div class="col-md-6">

      <h1> ToDos NO COMPLETADOS </h1>

      <% @todos.each do |t| %>
        <% if t.completed == false %>
          <ul class="list-group">
          <li class="list-group-item list-group-item-danger"> <%= t.description %> </li>
          </ul>
        <% end %>
      <% end %>

    </div>

    <div class="col-md-6">

      <h1> ToDos COMPLETADOS </h1>

      <% @todos.each do |t| %>
        <% if t.completed %>
          <ul class="list-group">
          <li class="list-group-item list-group-item-success"> <%= t.description %> </li>
          </ul>
        <% end %>
      <% end %>

    </div>

  </div>

</div>

app/views/todos/new.html.erb
<h1> Ingresar nuevo ToDo </h1>

<%= render 'form' %>

app/views/todos/show.html.erb
<h1> <%= "ID: ToDo #{@todo.id}" %> </h1>

<div class="container">

<h2> <%= "Descripción ToDo: #{@todo.description}" %> </h2>

<h2> <%= "Estado: #{@status}" %> </h2>

<h3> Creado: <%= time_ago_in_words @todo.created_at %> </h3>

</div>